package parser;

public enum TreeNodeType {
    NULL,
    // terminal
    IDENTIFIER, INT_CONST, STRING_CONST,
    MAIN, CONST, INT, BREAK, CONTINUE, IF, ELSE, WHILE, GETINT, PRINTF, RETURN, VOID,
    NOT, AND, OR, PLUS, MINUS, MULTIPLY, DIVIDE, MOD,
    LESS, LESS_EQUAL, GREATER, GREATER_EQUAL, EQUAL, NOT_EQUAL, ASSIGN, SEMICOLON, COMMA,
    LEFT_PAREN, RIGHT_PAREN, LEFT_BRACKET, RIGHT_BRACKET, LEFT_BRACE, RIGHT_BRACE,
    // nonterminal
    _COMPILE_UNIT_, _DECLARATION_, _BASIC_TYPE_, _CONST_DECLARATION_, _CONST_DEFINITION_, _CONST_INIT_VALUE_,
    _VAR_DECLARATION_, _VAR_DEFINITION_, _VAR_INIT_VALUE_, _FUNCTION_DEFINITION_, _MAIN_FUNCTION_DEFINITION_,
    _FUNCTION_RETURN_TYPE_, _FUNCTION_DEFINITION_PARAM_LIST_, _FUNCTION_DEFINITION_PARAM_, _BLOCK_, _BLOCK_ITEM_,
    _STATEMENT_, _EXPRESSION_, _CONDITION_, _LEFT_VALUE_, _PRIMARY_EXPRESSION_, _NUMBER_, _UNARY_EXPRESSION_,
    _FUNCTION_CALL_PARAM_LIST_, _MULTIPLY_EXPRESSION_, _ADD_EXPRESSION_, _RELATION_EXPRESSION_, _EQUAL_EXPRESSION_,
    _LOGIC_AND_EXPRESSION_, _LOGIC_OR_EXPRESSION_, _CONST_EXPRESSION_
}
