public class Token {
    TokenType type;
    String name;
    int lineNumber;
}

enum TokenType {
    IDENTIFIER, INTEGER_CONST, STRING_CONST,
    MAIN, CONST, INT, BREAK, CONTINUE, IF, ELSE, WHILE, GETINT, PRINTF, RETURN, VOID,
    NOT, AND, OR, PLUS, MINUS, MULTIPLY, DIVIDE, MOD,
    LESS, LESS_EQUAL, GREATER, GREATER_EQUAL, EQUAL, NOT_EQUAL,
    ASSIGN, SEMICOLON, COMMA,
    LEFT_PAREN, RIGHT_PAREN, LEFT_BRACKET, RIGHT_BRACKET, LEFT_BRACE, RIGHT_BRACE, UNKNOWN
}